### ISSUE TITLE
As a SO, I want to be able to see the user's first and last name vs. identikey

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1281]
## Context

We had this as an issue in FIT-1336, but now that identikeys are getting capitalized I think it makes more sense to implement https://www.drupal.org/project/realname than to debug LDAP.

> There is really no reason we are only dealing with identikey usernames. This info is returned 
> by LDAP. Anything beyond first/last should use a Person Node with entity reference.

## Process

1. Login to site as a [SO, ADMIN or DEV]
2. Click Express > Users

## Expected result

List of users includes users Display Name and Primary Affiliation from LDAP.  Users with access to this view can search by the display name or identikey.

![users___university_of_colorado_boulder](https://user-images.githubusercontent.com/385234/28640534-373e8a3c-7209-11e7-8a58-ec124ebc8dc5.png)

![edit_basic_page_teds___university_of_colorado_boulder](https://user-images.githubusercontent.com/385234/28640986-c8b44974-720a-11e7-8046-dc4a7ed59cf1.png)

## Current result

identikey shown

**Comment by kreynen** [comment]
https://github.com/CuBoulder/express/issues/1291 will update all users, but these can be tested independently.

**Comment by cathysnider** [comment]
https://www-dev.colorado.edu/p1d5e62ded73/

**Comment by cathysnider** [comment]
Acceptance Criteria:
- [ ] Site Owners can't see Devs or Admins
- [ ] Display Names and Affiliations, when changed, are changed back on re-login. (note that currently Display Names and Affiliations can be changed)

**Comment by kreynen** [comment]
added update for all users in CE, SO and EO roles on update and locked new fields on user/X/edit

**Comment by cathysnider** [comment]
@kreynen I am unable to login to any sites with feature 1281: 
- http://www-dev.colorado.edu/p1b47f518135/
- https://www-dev.colorado.edu/feature/1281
- https://www-dev.colorado.edu/p195d184a704

**Comment by cathysnider** [comment]
New Acceptance Criteria:
- [ ] Site Owners can't see Devs or Admins
- [ ] Display name cannot be changed
- [ ] Full Names and Primary Affiliation is added upon login
- [ ] 'Authored by' lookup works for name and identikey

**Comment by cathysnider** [comment]
Looks good.
