### ISSUE TITLE
As a SM, I want faster page loads 

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1433]
## Context

This goes back to Apr 09, 2012 when Matt created https://cuboulder.atlassian.net/browse/UCB-27

He was more concerned with the performance in specific countries, but centralizing commons assets will improve the avg page load time for everyone and reduce the number of http requests the servers have to handle.

We've been slowly improving the page load time of Express with most releases and improvements to infrastructure, but it you look at the avg page load time from last year to this year we've only managed to shave .3 seconds off the page load time.

![screen shot 2017-08-25 at 11 04 16 am](https://user-images.githubusercontent.com/385234/29724279-2d4ecc6a-8985-11e7-9113-5159d00b4248.png)

This view excludes oit, catalog and 404s... things we know changed.

Some high traffic pages like /vist went up from 4.54 to 5.42.  

Since it's clear, we are not going to move all Express sites to D8 in 2018, we can make our D7 offering as good as it can possibly be. 

## Process

- [ ] Identify largest common assets (jquery, fontawesome, etc)
- [ ] Create repo of those assets
- [ ] Serve that repo from the homepage with an extremely long cache time so Varnish is handling the load or server it from something like assets.colorado.edu hosted on Pantheon.
- [ ] Update the Express code so that the commons assets aren't included in the each site's aggregated js.
- [ ]

**Comment by alexfinnarn** [comment]
If the assets are hosted externally, then grabbing them for testing can cause intermittent failures, but since prod would rely on the same resource it should be safe to make requests to that server.
