### ISSUE TITLE
Automated Testing Meeting Follow-up

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#2011]
- [x] Share Lastpass account info
- [ ] Link tutorial corrections to writing behat tests based off of training scripts - #2012
- [ ] Make a bundle/repo for visual regression tests based off of Sauce Labs screenshots - #2013
- [ ] Look at removing window from top of Chrome, Safari, Firefox screenshots and other Sauce YAML configurations - #2014

Meeting notes: https://docs.google.com/document/d/1Uectc1HBdan814gsi5Yd_SqlQ2inoMQULT-sAqzLfBU/edit

**Comment by alexfinnarn** [comment]
all of these checkboxes have been completed or the referenced issue is now closed.
