### ISSUE TITLE
As a SO/CE, I would like to create Block Sections with a parallax background effect

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#894]
## Context

One of the design trends that has been requested in Web Express is a parallax background effect.  We can classify this into two versions/types:

- Simple: Background of element remains fixed while user scrolls the page. While this is not true parallax, it is often referred to as such.
- Advanced: Background scrolls at a different speed as the user scrolls the page.

The simple version can be implemented with CSS by setting the background to be fixed instead of scroll. The advanced version requires javascript to not only move the background position at a different speed while the user scrolls, but to make sure the image does not move out of the "window" or "frame" while the user scrolls.  Advanced parallax elements also need to take into account as to where they are on the page so the proper scrolling range happens while the element is in view.

Recommend we start with the simple version.

## Example

![ezgif-1-7778571a29](https://cloud.githubusercontent.com/assets/349713/23757949/707c5c88-04a5-11e7-9f9f-e15866243e43.gif)

**Comment by cathysnider** [comment]
https://www-dev.colorado.edu/p10e92e332f4/

**Comment by cathysnider** [comment]
Acceptance Criteria:

- [ ] Block Sections set to 'Parallax' have the parallax effect
- [ ] Block Sections set to 'Scroll' have the scroll effect.
- [ ] Block Sections set to 'Fixed' have the Fixed effect.
- [ ] Other .....

**Comment by cathysnider** [comment]
Acceptance Criteria:

- [ ] Block Sections set to 'Parallax' have the parallax effect
- [ ] Block Sections set to 'Scroll' have the scroll effect.
- [ ] Block Sections set to 'Fixed' have the Fixed effect.
- [ ] Other .....
