### ISSUE TITLE
As a SO/CE I would like to create a various styles of layouts with content grids

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#914]
## Context

Content grids, with each cell containing an image, title and text, could be formatted into various types of layouts/displays.

Currently, the only content grid display option is columns.  By adding a configurable style option, a content grid block can be displayed differently.

## Examples

![contentgrids](https://cloud.githubusercontent.com/assets/349713/23911115/64045212-08a1-11e7-9349-010007b55872.jpg)

## Possible Solution

- Add a style field to content grid blocks.
- Template each style.
- Add css based on style.

**Comment by cathysnider** [comment]
Acceptance Criteria:
- [ ] Columns
  - [ ] Can vary number of columns
  - [ ] Can vary image styles
- [ ] Overlay
- [ ] Large Teaser
- [ ] Large Teaser Alternate
- [ ] Feature
- [ ] Offset
- [ ] Cards
- [ ] Teaser

**Comment by cathysnider** [comment]
Test Results:
Mostly awesome except for the following problems:
Columns: Good except for the 5-column layout. It does one column instead.  
Overlay: Beautiful except 1) display breaks if no pic is uploaded. 2) You can't change number of columns or the image style. It chooses what was set by 'Columns' when you started making the grid. 
Cards:  Good except for the 5-column layout. It does one column instead.  
Tiles: going away so never mind
Tiles Alternative: The second image/text combo always looks weird no matter what you do.

**Comment by cathysnider** [comment]
I still think you shouldn't be able to save Overlay or Feature unless all have images
